# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

# The changelog is managed by release-please
changelog:
  disable: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: s9k
    main: cmd/s9k/s9k.go

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: s9k 
    description: A CLI tool for displaying AWS services 
    homepage: https://github.com/oslokommune/s9k
    goarm: 6
    goamd64: v1
    skip_upload: false
    repository:
      owner: bsek
      name: s9k
      branch: main
      pull_request:
        enabled: false
        draft: false
    directory: Formula
    install: |
      bin.install "s9k"
