# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S9k < Formula
  desc "A CLI tool for displaying AWS services"
  homepage "https://github.com/bsek/s9k"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/bsek/s9k/releases/download/v0.0.4/s9k_Darwin_x86_64.tar.gz"
      sha256 "4e95885328ec9a32f6681a023e5b67dbc5b14616c65e832565aca22c81541103"

      def install
        bin.install "s9k"
      end
    end
    on_arm do
      url "https://github.com/bsek/s9k/releases/download/v0.0.4/s9k_Darwin_arm64.tar.gz"
      sha256 "4c4042a992fb6ed04af9687eed9e28ad0d5a1ee990523a0e36a33bbc32f024e4"

      def install
        bin.install "s9k"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bsek/s9k/releases/download/v0.0.4/s9k_Linux_x86_64.tar.gz"
        sha256 "ca50ae0865f7c5e10c32b7f5a062cfe0f045cd636cc6e7ab88a64fe8ba69de62"

        def install
          bin.install "s9k"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bsek/s9k/releases/download/v0.0.4/s9k_Linux_arm64.tar.gz"
        sha256 "1ba230a608f6bc54da0b5168b5f375d1b4494e6d261b0b44e7532cf91878adb0"

        def install
          bin.install "s9k"
        end
      end
    end
  end
end
